swagger: '2.0'
info:
  description: Vehicle APis
  version: 1.0.0
  title: Vehicle API's
basePath: /api/

tags:
  - name: Vehicle APIs
    description: 

paths:
  /searchVehicles:
    post:
      tags:
        - search
      summary: Search Vehicle
      description: 'Search Vehicle with this API'
      operationId: Search Vehicle
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: search_string
          type: string
          required: true
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request

  /vehicleSales:
    get:
      tags:
        - sales
      summary: Sales Vehicle
      description: 'Sales Vehicle '
      operationId: Sales Vehicle
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
  
securityDefinitions:
  api_key:
    type: apiKey
    name: Authorization
    in: header